# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: Lingyu Li  #'s Website
  params:
    description: Postdoctoral Fellow in Bioinformatics at HKU. Research on spatial transcriptomics, sparse statistical learning, and biomarker discovery.
  menu:
    # Navigation Links
    #   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
    #     desired widget in your `content/home/` folder.
    #   The weight parameter defines the order that the links will appear in.

    main:
      - name: Biography
        url: '#about'
        weight: 10
      - name: Experience
        url: '#experiences'
        weight: 20
      - name: News
        url: '#posts'
        weight: 30
      - name: Conferences
        url: '#conferences'
        weight: 40
      - name: Publications
        url: '#publications'
        weight: 50
      - name: Projects
        url: '#projects'
        weight: 60
      - name: Awards
        url: '#competitions'
        weight: 70
      - name: Contact
        url: '#contact'
        weight: 80

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 李苓玉
  params:
    description: 香港大学生物信息学博士后，研究方向包括空间转录组学、稀疏统计学习与生物标志物识别。
  menu:
    # Navigation Links
    #   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
    #     desired widget in your `content/home/` folder.
    #   The weight parameter defines the order that the links will appear in.

    main:
      - name: 简介
        url: '#about'
        weight: 10
      - name: 教育经历
        url: '#experiences'
        weight: 20
      - name: 生活日常
        url: '#posts'
        weight: 30
      - name: 会议
        url: '#conferences'
        weight: 40
      - name: 论文
        url: '#publications'
        weight: 50
      - name: 项目
        url: '#projects'
        weight: 60
      - name: 荣誉
        url: '#competitions'
        weight: 70
      - name: 联系
        url: '#contact'
        weight: 80
